ros_topic:
  lidar: "/points_raw"
  imu: "/imu_correct"

param_acc_value_scale: 1.0

param_lidar_type: "LIDAR_TYPE_urbannav_new_velodyne_HDL32E"
param_detect_range: 200.0
param_detect_blind: 4.0

flg_extrinsic_bwtween_l_i_use_rot: true
# extrinsic_rot_l_i: 
# extrinsic_quat_l_i:  # 顺序 x y z w
# extrinsic_trans_l_i: 
# extrinsic_rot_l_i: [1, 0, 0,
#                   0, 1, 0,
#                   0, 0, 1]
# extrinsic_quat_l_i: [ 0, 0, 0, 1] # 顺序 x y z w
# extrinsic_trans_l_i: [ 0.04165, 0.02326, -0.0284]
extrinsic_rot_i_l: [  1.0, 0,  0, 
                   0,  1.0,  0, 
                   0,  0,  1.0]
# extrinsic_quat_i_l: [ 0.0, 0.0, 0.0, -1.0] # 顺序 x y z w
extrinsic_trans_i_l: [  0, 0, 0]

# ################## Extrinsic parameter between IMU and LiDAR##################
# body_T_LiDAR: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 2.67949e-08, -1,  0, 0,
#            1,  2.67949e-08,  0, 0,
#            0,  0,  1, -0.28, 
#            0., 0., 0., 1 ]

# imu_noise:
#   acc_std: 0.03
#   gyr_std: 0.03
#   ba_std: 0.003
#   bg_std: 0.003
# imu_noise:
#   acc_std: 0.05
#   gyr_std: 0.05
#   ba_std: 0.005
#   bg_std: 0.005
imu_noise:
  acc_std: 3.9939570888238808e-03
  gyr_std: 1.5636343949698187e-03
  ba_std: 6.4356659353532566e-05
  bg_std: 3.5640318696367613e-05
# imu_noise:
#   acc_std: 0.5
#   gyr_std: 0.5
#   ba_std: 0.05
#   bg_std: 0.05
# imu_noise:
#   acc_std: 1
#   gyr_std: 1
#   ba_std: 0.1
#   bg_std: 0.1

